"""Report generator for vulnerability findings."""

import json
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional
from .config import Config


class Reporter:
    """Generate vulnerability audit reports."""

    def __init__(self, config: Optional[Config] = None):
        """Initialize reporter."""
        self.config = config or Config()
        self.output_dir = self.config.get_output_dir()
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        target: str,
        cve_data: Dict[str, Any],
        threat_model: Dict[str, Any],
        findings: List[Dict[str, Any]],
        format: str = "markdown"
    ) -> str:
        """Generate vulnerability audit report."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        target_slug = target.replace("/", "_").replace(":", "_").replace("/", "_")
        filename = f"llm_audit_{target_slug}_{timestamp}.{format}"

        if format == "markdown":
            content = self._generate_markdown(target, cve_data, threat_model, findings)
        elif format == "json":
            content = self._generate_json(target, cve_data, threat_model, findings)
        else:
            content = self._generate_markdown(target, cve_data, threat_model, findings)

        output_path = self.output_dir / filename
        with open(output_path, 'w') as f:
            f.write(content)

        print(f"\n[+] Report saved to: {output_path}")
        return str(output_path)

    def _generate_markdown(
        self,
        target: str,
        cve_data: Dict[str, Any],
        threat_model: Dict[str, Any],
        findings: List[Dict[str, Any]]
    ) -> str:
        """Generate Markdown report."""
        lines = [
            "# LLM-Audit Vulnerability Research Report",
            "",
            f"**Target:** {target}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Finding Count:** {len(findings)}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            self._generate_summary(findings),
            "",
            "---",
            "",
            "## CVE/Advisory Analysis",
            "",
            cve_data.get("summary", "No CVEs found."),
            "",
            f"Found **{cve_data.get('count', 0)}** security advisories.",
            "",
            "---",
            "",
            "## Threat Model",
            "",
            self._format_threat_model(threat_model),
            "",
            "---",
            "",
            "## Vulnerability Findings",
            "",
        ]

        if not findings:
            lines.append("*No vulnerabilities found in this audit.*")
        else:
            # Group by severity
            severity_order = ["Critical", "High", "Medium", "Low", "Info"]
            grouped = {}

            for f in findings:
                sev = f.get("severity", "Info").title()
                if sev not in grouped:
                    grouped[sev] = []
                grouped[sev].append(f)

            for sev in severity_order:
                if sev in grouped:
                    lines.append(f"### {sev} Severity ({len(grouped[sev])})")
                    lines.append("")

                    for i, finding in enumerate(grouped[sev], 1):
                        lines.append(f"#### Finding {i}: {finding.get('bug_class', 'Unknown')}")
                        lines.append("")
                        lines.append(f"**Location:** `{finding.get('location', 'N/A')}`")
                        lines.append("")
                        lines.append(f"**Issue:** {finding.get('issue', 'N/A')}")
                        lines.append("")
                        lines.append(f"**Impact:** {finding.get('impact', 'N/A')}")
                        lines.append("")
                        if finding.get('poc'):
                            lines.append(f"**Proof of Concept:**")
                            lines.append("```")
                            lines.append(finding.get('poc', ''))
                            lines.append("```")
                            lines.append("")
                        lines.append("---")
                        lines.append("")

        # Add recommendations
        lines.extend([
            "---",
            "",
            "## Recommendations",
            "",
            self._generate_recommendations(findings, threat_model),
            "",
            "---",
            "",
            "*Report generated by LLM-Audit*",
        ])

        return "\n".join(lines)

    def _generate_summary(self, findings: List[Dict[str, Any]]) -> str:
        """Generate executive summary."""
        if not findings:
            return "No vulnerabilities were identified in this audit."

        severity_counts = {}
        for f in findings:
            sev = f.get("severity", "Info").title()
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        summary = f"This audit identified **{len(findings)}** potential security issues:\n\n"

        for sev in ["Critical", "High", "Medium", "Low"]:
            if sev in severity_counts:
                summary += f"- **{sev}:** {severity_counts[sev]}\n"

        return summary

    def _format_threat_model(self, model: Dict[str, Any]) -> str:
        """Format threat model as markdown."""
        lines = []

        for item in model.get("threat_model", []):
            sev = item.get("severity", "UNKNOWN")
            bug = item.get("bug_class", "Unknown")
            desc = item.get("description", "")

            lines.append(f"- **[{sev}]** {bug}: {desc}")

        lines.append("")
        lines.append("**Recommended Testing Order:**")
        for i, bug in enumerate(model.get("priority", [])[:5], 1):
            lines.append(f"  {i}. {bug}")

        return "\n".join(lines)

    def _generate_recommendations(self, findings: List[Dict[str, Any]], model: Dict[str, Any]) -> str:
        """Generate recommendations based on findings."""
        lines = []

        if findings:
            lines.append("1. **Review High/Critical Findings First** - Prioritize remediation by severity")
            lines.append("2. **Verify Exploitability** - Validate each finding in a test environment")
            lines.append("3. **Check Similar Code** - Search for similar patterns across the codebase")

        bug_classes = set(f.get("bug_class", "") for f in findings)
        if "IDOR" in bug_classes or "Authentication Bypass" in bug_classes:
            lines.append("4. **Access Control Audit** - Review all authorization checks")
        if "XSS" in bug_classes:
            lines.append("5. **Input Validation** - Implement proper input sanitization")
        if "SQL Injection" in bug_classes:
            lines.append("6. **Use Parameterized Queries** - Replace string concatenation in SQL")

        if not lines:
            lines.append("1. Continue regular security testing")
            lines.append("2. Keep dependencies up to date")
            lines.append("3. Implement security code review process")

        return "\n".join(lines)

    def _generate_json(
        self,
        target: str,
        cve_data: Dict[str, Any],
        threat_model: Dict[str, Any],
        findings: List[Dict[str, Any]]
    ) -> str:
        """Generate JSON report."""
        report = {
            "target": target,
            "timestamp": datetime.now().isoformat(),
            "summary": {
                "total_findings": len(findings),
                "by_severity": {}
            },
            "cve_analysis": cve_data,
            "threat_model": threat_model,
            "findings": findings
        }

        # Count by severity
        for f in findings:
            sev = f.get("severity", "Info").title()
            report["summary"]["by_severity"][sev] = report["summary"]["by_severity"].get(sev, 0) + 1

        return json.dumps(report, indent=2)


def generate_report(
    target: str,
    cve_data: Dict[str, Any],
    threat_model: Dict[str, Any],
    findings: List[Dict[str, Any]],
    config: Optional[Config] = None,
    format: str = "markdown"
) -> str:
    """Convenience function to generate report."""
    reporter = Reporter(config)
    return reporter.generate_report(target, cve_data, threat_model, findings, format)